/*
 Copyright (c) 2026. Giulio Cocconi

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include <core/fstWrapper.hpp>
#include <utils/transparent_string.hpp>

/**
 * @class FstTraceWriter
 * @brief Writes named vector signals from already-sampled FST value strings.
 *
 * This class owns the generic FST trace behavior: signal registration, value
 * normalization, timestamp emission, and flushing. Circuit-specific adapters can use
 * it without exposing libfst handles or hierarchy construction to their callers.
 */
class FstTraceWriter final {
public:
  /**
   * @brief Static description of a signal to register in the FST hierarchy.
   */
  struct TraceSignal {
    /**
     * Signal name as it should appear under the top-level FST scope.
     */
    std::string name;

    /**
     * Number of bits in the emitted vector. Zero-width signals are ignored.
     */
    std::size_t width = 1;
  };

  /**
   * @brief FST file metadata and hierarchy options.
   */
  struct Options {
    /**
     * Top-level FST scope name. When empty, "SILICON" is used.
     */
    std::string topScopeName;

    /**
     * FST timescale exponent. The default represents nanoseconds.
     */
    int timescale = -9;

    /**
     * Metadata string stored in the FST header.
     */
    std::string version = std::string("Generated by SILICON ") + SILICON_VERSION;
  };

  FstTraceWriter(std::string_view                fileName,
                 const std::vector<TraceSignal>& traceSignals);

  /**
   * @brief Creates an FST file and registers all non-zero-width trace signals.
   *
   * The constructor completes the FST hierarchy immediately. Subsequent calls to
   * emitSnapshot() only emit timestamped value changes for the registered signals.
   *
   * @param fileName Destination FST file path.
   * @param traceSignals Ordered signal descriptors. This order defines value indexes for
   * snapshots.
   * @param options File metadata and top-level scope settings.
   */
  FstTraceWriter(std::string_view                fileName,
                 const std::vector<TraceSignal>& traceSignals, Options options);

  FstTraceWriter(const FstTraceWriter&)            = delete;
  FstTraceWriter& operator=(const FstTraceWriter&) = delete;

  FstTraceWriter(FstTraceWriter&&) noexcept            = default;
  FstTraceWriter& operator=(FstTraceWriter&&) noexcept = default;

  /**
   * @brief Emits one timestamped snapshot of already-sampled signal values.
   *
   * Values are matched to registered signals by index. Missing or empty values are
   * emitted as unknowns, invalid characters are normalized to unknowns, shorter values
   * are left-padded, and longer values keep their rightmost bits.
   *
   * @param time Timestamp for this snapshot.
   * @param values Encoded FST/VCD-style values using 0, 1, x, and z symbols.
   */
  void emitSnapshot(uint64_t time, std::span<const std::string> values);

  /**
   * @brief Flushes pending FST data so external tools can read recent snapshots.
   */
  void flush();

  /**
   * @brief Returns the libfst handle associated with a registered signal name.
   */
  [[nodiscard]] std::optional<fstHandle> handleForSignal(std::string_view name) const;

  /**
   * @brief Number of non-zero-width signals registered in the FST hierarchy.
   */
  [[nodiscard]] std::size_t signalCount() const { return registeredSignals.size(); }

private:
  struct RegisteredSignal {
    std::string name;
    std::size_t valueIndex;
    std::size_t width;
    fstHandle   handle;
  };

  [[nodiscard]] static std::string normalizeValue(std::string_view value,
                                                  std::size_t      width);

  std::vector<RegisteredSignal>              registeredSignals;
  std::unordered_map<std::string, fstHandle, TransparentStringHash,
                     TransparentStringEqual>
      handlesBySignalName;
  FstDataWriter                              writer;
};
